/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: (typeof import('ant-design-vue/es'))['Button']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    ALayout: (typeof import('ant-design-vue/es'))['Layout']
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent']
    ALayoutFooter: (typeof import('ant-design-vue/es'))['LayoutFooter']
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader']
    ALayoutSider: (typeof import('ant-design-vue/es'))['LayoutSider']
    Header: (typeof import('./../components/Header.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Sider: (typeof import('./../components/Sider.vue'))['default']
    Weather: (typeof import('./../components/Weather.vue'))['default']
  }
}
