/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: (typeof import('ant-design-vue/es'))['Button']
    ACarousel: (typeof import('ant-design-vue/es'))['Carousel']
    ACol: (typeof import('ant-design-vue/es'))['Col']
    ACollapse: (typeof import('ant-design-vue/es'))['Collapse']
    ACollapsePanel: (typeof import('ant-design-vue/es'))['CollapsePanel']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    ADescriptions: (typeof import('ant-design-vue/es'))['Descriptions']
    ADescriptionsItem: (typeof import('ant-design-vue/es'))['DescriptionsItem']
    AImage: (typeof import('ant-design-vue/es'))['Image']
    ALayout: (typeof import('ant-design-vue/es'))['Layout']
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent']
    ALayoutFooter: (typeof import('ant-design-vue/es'))['LayoutFooter']
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader']
    ALayoutSider: (typeof import('ant-design-vue/es'))['LayoutSider']
    AModal: (typeof import('ant-design-vue/es'))['Modal']
    AProgress: (typeof import('ant-design-vue/es'))['Progress']
    ARow: (typeof import('ant-design-vue/es'))['Row']
    ASpace: (typeof import('ant-design-vue/es'))['Space']
    ATable: (typeof import('ant-design-vue/es'))['Table']
    ATimeline: (typeof import('ant-design-vue/es'))['Timeline']
    ATimelineItem: (typeof import('ant-design-vue/es'))['TimelineItem']
    ATypographyText: (typeof import('ant-design-vue/es'))['TypographyText']
    ATypographyTitle: (typeof import('ant-design-vue/es'))['TypographyTitle']
    Header: (typeof import('./../components/Header.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Sider: (typeof import('./../components/Sider.vue'))['default']
    Weather: (typeof import('./../components/Weather.vue'))['default']
  }
}
