// @unocss-include
export const icons = [
  'i-material-symbols:audio-file',
  'i-material-symbols:video-file',
  'i-mdi:file-powerpoint',
  'i-mdi:file-excel',
  'i-mdi:file-word',
  'i-mdi:file-pdf',
  'i-mdi:file',
  'i-ant-design:close-circle-filled',
  'i-ant-design:menu-outlined',
  'i-zondicons:show-sidebar',
  'i-gis:map-legend',
  'i-material-symbols:map',
  'i-bi:bezier2',
  'i-mdi:circle-outline',
  'i-mdi:ellipse-outline',
  'i-material-symbols:location-on',
  'i-ph:polygon',
  'i-material-symbols:polyline-outline',
  'i-mdi:vector-rectangle',
  'i-ph:text-t',
  'i-mdi:image-text',
  'i-material-symbols:image-outline',
]
