/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: (typeof import('ant-design-vue/es'))['Button']
    ACarousel: (typeof import('ant-design-vue/es'))['Carousel']
    ACollapse: (typeof import('ant-design-vue/es'))['Collapse']
    ACollapsePanel: (typeof import('ant-design-vue/es'))['CollapsePanel']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    ADescriptions: (typeof import('ant-design-vue/es'))['Descriptions']
    ADescriptionsItem: (typeof import('ant-design-vue/es'))['DescriptionsItem']
    AEmpty: (typeof import('ant-design-vue/es'))['Empty']
    AForm: (typeof import('ant-design-vue/es'))['Form']
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem']
    AFormItemRest: (typeof import('ant-design-vue/es'))['FormItemRest']
    AImage: (typeof import('ant-design-vue/es'))['Image']
    AInput: (typeof import('ant-design-vue/es'))['Input']
    AInputGroup: (typeof import('ant-design-vue/es'))['InputGroup']
    AInputNumber: (typeof import('ant-design-vue/es'))['InputNumber']
    AMenu: (typeof import('ant-design-vue/es'))['Menu']
    AModal: (typeof import('ant-design-vue/es'))['Modal']
    AProgress: (typeof import('ant-design-vue/es'))['Progress']
    ARadio: (typeof import('ant-design-vue/es'))['Radio']
    ARadioGroup: (typeof import('ant-design-vue/es'))['RadioGroup']
    ASelect: (typeof import('ant-design-vue/es'))['Select']
    ASpace: (typeof import('ant-design-vue/es'))['Space']
    ASpin: (typeof import('ant-design-vue/es'))['Spin']
    ASwitch: (typeof import('ant-design-vue/es'))['Switch']
    ATable: (typeof import('ant-design-vue/es'))['Table']
    ATextarea: (typeof import('ant-design-vue/es'))['Textarea']
    ATimeline: (typeof import('ant-design-vue/es'))['Timeline']
    ATimelineItem: (typeof import('ant-design-vue/es'))['TimelineItem']
    ATooltip: (typeof import('ant-design-vue/es'))['Tooltip']
    AUpload: (typeof import('ant-design-vue/es'))['Upload']
    Header: (typeof import('./../client/src/components/Header.vue'))['default']
    Layer: (typeof import('./../client/src/components/Layer.vue'))['default']
    Map: (typeof import('./../client/src/components/Map.vue'))['default']
    Menu: (typeof import('./../client/src/components/Menu.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Sider: (typeof import('./../client/src/components/Sider.vue'))['default']
    Weather: (typeof import('./../client/src/components/Weather.vue'))['default']
  }
}
