/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: (typeof import('ant-design-vue/es'))['Alert']
    AButton: (typeof import('ant-design-vue/es'))['Button']
    ACarousel: (typeof import('ant-design-vue/es'))['Carousel']
    ACheckboxGroup: (typeof import('ant-design-vue/es'))['CheckboxGroup']
    ACollapse: (typeof import('ant-design-vue/es'))['Collapse']
    ACollapsePanel: (typeof import('ant-design-vue/es'))['CollapsePanel']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    ADescriptions: (typeof import('ant-design-vue/es'))['Descriptions']
    ADescriptionsItem: (typeof import('ant-design-vue/es'))['DescriptionsItem']
    ADivider: (typeof import('ant-design-vue/es'))['Divider']
    ADropdown: (typeof import('ant-design-vue/es'))['Dropdown']
    AEmpty: (typeof import('ant-design-vue/es'))['Empty']
    AForm: (typeof import('ant-design-vue/es'))['Form']
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem']
    AFormItemRest: (typeof import('ant-design-vue/es'))['FormItemRest']
    AImage: (typeof import('ant-design-vue/es'))['Image']
    AInput: (typeof import('ant-design-vue/es'))['Input']
    AInputGroup: (typeof import('ant-design-vue/es'))['InputGroup']
    AInputNumber: (typeof import('ant-design-vue/es'))['InputNumber']
    AInputSearch: (typeof import('ant-design-vue/es'))['InputSearch']
    ALayout: (typeof import('ant-design-vue/es'))['Layout']
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent']
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader']
    ALayoutSider: (typeof import('ant-design-vue/es'))['LayoutSider']
    AMenu: (typeof import('ant-design-vue/es'))['Menu']
    AMenuItem: (typeof import('ant-design-vue/es'))['MenuItem']
    AModal: (typeof import('ant-design-vue/es'))['Modal']
    APopconfirm: (typeof import('ant-design-vue/es'))['Popconfirm']
    AProgress: (typeof import('ant-design-vue/es'))['Progress']
    ARadio: (typeof import('ant-design-vue/es'))['Radio']
    ARadioGroup: (typeof import('ant-design-vue/es'))['RadioGroup']
    ASelect: (typeof import('ant-design-vue/es'))['Select']
    ASpace: (typeof import('ant-design-vue/es'))['Space']
    ASpin: (typeof import('ant-design-vue/es'))['Spin']
    ASwitch: (typeof import('ant-design-vue/es'))['Switch']
    ATable: (typeof import('ant-design-vue/es'))['Table']
    ATag: (typeof import('ant-design-vue/es'))['Tag']
    ATextarea: (typeof import('ant-design-vue/es'))['Textarea']
    ATimeline: (typeof import('ant-design-vue/es'))['Timeline']
    ATimelineItem: (typeof import('ant-design-vue/es'))['TimelineItem']
    ATooltip: (typeof import('ant-design-vue/es'))['Tooltip']
    ATree: (typeof import('ant-design-vue/es'))['Tree']
    ATreeSelect: (typeof import('ant-design-vue/es'))['TreeSelect']
    AUpload: (typeof import('ant-design-vue/es'))['Upload']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
