/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: (typeof import('ant-design-vue/es'))['Alert']
    AButton: (typeof import('ant-design-vue/es'))['Button']
    ACarousel: (typeof import('ant-design-vue/es'))['Carousel']
    ACol: (typeof import('ant-design-vue/es'))['Col']
    ACollapse: (typeof import('ant-design-vue/es'))['Collapse']
    ACollapsePanel: (typeof import('ant-design-vue/es'))['CollapsePanel']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    ADescriptions: (typeof import('ant-design-vue/es'))['Descriptions']
    ADescriptionsItem: (typeof import('ant-design-vue/es'))['DescriptionsItem']
    ADropdown: (typeof import('ant-design-vue/es'))['Dropdown']
    AForm: (typeof import('ant-design-vue/es'))['Form']
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem']
    AImage: (typeof import('ant-design-vue/es'))['Image']
    AInput: (typeof import('ant-design-vue/es'))['Input']
    ALayout: (typeof import('ant-design-vue/es'))['Layout']
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent']
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader']
    ALayoutSider: (typeof import('ant-design-vue/es'))['LayoutSider']
    AMenu: (typeof import('ant-design-vue/es'))['Menu']
    AMenuItem: (typeof import('ant-design-vue/es'))['MenuItem']
    AModal: (typeof import('ant-design-vue/es'))['Modal']
    AProgress: (typeof import('ant-design-vue/es'))['Progress']
    ARow: (typeof import('ant-design-vue/es'))['Row']
    ASpace: (typeof import('ant-design-vue/es'))['Space']
    ASpin: (typeof import('ant-design-vue/es'))['Spin']
    ASwitch: (typeof import('ant-design-vue/es'))['Switch']
    ATable: (typeof import('ant-design-vue/es'))['Table']
    ATag: (typeof import('ant-design-vue/es'))['Tag']
    ATimeline: (typeof import('ant-design-vue/es'))['Timeline']
    ATimelineItem: (typeof import('ant-design-vue/es'))['TimelineItem']
    ATree: (typeof import('ant-design-vue/es'))['Tree']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
